### ISSUE TITLE
Compat issues

### ISSUE THREAD

**Issue by Swifty744** [Tynoxs/BuildersDelight#26]
If you run builders delight latest version 1.20.1 Forge with better compat the game crashes. If you need a better way to figure out the issue or my logs lemme know

**Comment by Tynoxs** [comment]
Do you mean every compat? 
But yes, could you pleave provide the crash log? 

Edit: It's because the furniture kit is now using the vanilla item class, instead of having it's own class.
Wait for a every compat update or use the previous version of Builder's Delight until every compat is updated.

Thank you for reporting.
